name: Publish to PyPI
on:
  release:
    types: [published]
permissions:
  id-token: write
jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3.3
      - name: Publish
        run: |
          pdm publish