name: Create GitHub release
permissions:
  id-token: write
on:
  push:
    tags:
      - "*"
    branches-ignore:
      - "*"
env:
  GITHUB_REF_NAME: ${{ github.ref_name }}
jobs:
  github-release:
    runs-on: ubuntu-latest
    name: Create Latest GitHub Release
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Check Tag for Release Type
        id: tag-type
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs\/tags\/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "releaseType=latest" >> $GITHUB_OUTPUT
          fi
          if [[ ${{ github.event.ref }} =~ ^refs\/tags\/[0-9]+\.[0-9]+\.[0-9]*[a-z]+[0-9]*$ ]]; then
            echo "releaseType=dev" >> $GITHUB_OUTPUT
          fi
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3.3
      - name: Generate wheel artifacts
        id: generate-artifacts
        run: |
          pdm build
      - name: Install dependencies
        run: |
          pdm sync -G ci
      - name: Generate release notes
        run: |
          pdm run cz changelog $GITHUB_REF_NAME --file RELEASE-NOTES.md
          cat RELEASE-NOTES.md
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ steps.tag-type.outputs.releaseType == 'latest' }}
          body_path: RELEASE-NOTES.md
          generate_release_notes: false
          files: |
            dist/*
  publish-to-pypi:
    runs-on: ubuntu-latest
    needs: [github-release]
    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3.3
      - name: Publish
        run: |
          pdm publish