name: Check for Commits Requiring Tags
on:
  push:
    branches:
      - main
jobs:
  checks:
    uses: ./.github/workflows/push-checks.yml

  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    needs: [checks]
    permissions:
      contents: write
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "partialdispatch[bot]"
          git config --global user.email "dominic.weldon+partialdispatch@gmail.com"
      - name: Check out
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.COMMIT_KEY }}
          fetch-depth: 0
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3.3
      - name: Install dependencies
        run: |
          pdm sync -G ci
      - name: Bump version
        run: |
          pdm run cz --no-raise 21 bump --yes --changelog --check-consistency